CREATE DATABASE shopapp;
USE shopapp;

-- TẠO BẢNG
CREATE TABLE loaisanpham 
(
    MALOAISANPHAM INT PRIMARY KEY AUTO_INCREMENT,
    TENLOAISANPHAM VARCHAR(255) NOT NULL
);

CREATE TABLE thuonghieu
(
    MATHUONGHIEU INT PRIMARY KEY AUTO_INCREMENT,
    TENTHUONGHIEU VARCHAR(40)
);

CREATE TABLE sanpham 
(
    MASANPHAM INT PRIMARY KEY AUTO_INCREMENT,
    TENSANPHAM VARCHAR(255) NOT NULL,
    GIA INT NOT NULL,
    MATHUONGHIEU INT NOT NULL,
    MOTA VARCHAR(500) DEFAULT '',
    SOLUONGTONKHO INT,
    NGAYTAO DATETIME,
    CHINHSUA DATETIME,
    MALOAISANPHAM INT,
    THUMBNAIL VARCHAR(300) DEFAULT '',
    CONSTRAINT fk_loaisanpham FOREIGN KEY (MALOAISANPHAM) REFERENCES loaisanpham(MALOAISANPHAM),
    CONSTRAINT fk_mathuonghieu FOREIGN KEY (MATHUONGHIEU) REFERENCES thuonghieu(MATHUONGHIEU)
);

CREATE TABLE hinhanh
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MASANPHAM INT,
    MALOAISANPHAM INT,
    TENHINHANH VARCHAR(300),
    CONSTRAINT fk_hinhanh_sanpham FOREIGN KEY(MASANPHAM) REFERENCES sanpham(MASANPHAM) ON DELETE CASCADE,
    CONSTRAINT fk_hinhanh_loaisanpham FOREIGN KEY(MALOAISANPHAM) REFERENCES loaisanpham(MALOAISANPHAM) ON DELETE CASCADE
);

CREATE TABLE accounts
(
    USERID INT PRIMARY KEY AUTO_INCREMENT,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) DEFAULT '',
    FULLNAME VARCHAR(255) DEFAULT '',
    DIACHI VARCHAR(255) DEFAULT '',
    SODIENTHOAI VARCHAR(15) NOT NULL,
    NGAYTAO DATETIME,
    CHINHSUA DATETIME,
    NGAYSINH DATE,
    profile_image VARCHAR(500) DEFAULT NULL,
    IS_ACTIVE BIT DEFAULT 1,
    FACEBOOK_ACCOUNT_ID VARCHAR(100) DEFAULT NULL,
    GOOGLE_ACCOUNT_ID VARCHAR(100) DEFAULT NULL,
    ROLENAME BIT
);

CREATE TABLE tokens
(
    TOKEN_ID INT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(500) UNIQUE NOT NULL,
    TOKEN_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DATE DATETIME,
    REVOKED BIT DEFAULT 1,
    EXPIRED BIT DEFAULT 1,
    USERID INT,
    CONSTRAINT fk_tokens_accounts FOREIGN KEY (USERID) REFERENCES accounts(USERID)
);

CREATE TABLE social_accounts
(
    SOCIAL_ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROVIDER VARCHAR(20) NOT NULL COMMENT 'tên nhà social network',
    PROVIDER_ID VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL COMMENT 'email tài khoản',
    NAME VARCHAR(100) NOT NULL COMMENT 'tên người dùng',
    USERID INT,
    CONSTRAINT fk_social_accounts_accounts FOREIGN KEY (USERID) REFERENCES accounts(USERID)
);

CREATE TABLE donhang (
    MADONHANG INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT,
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) DEFAULT '',
    SODIENTHOAI VARCHAR(15) NOT NULL,
    DIACHI VARCHAR(200) NOT NULL,
    GHICHU VARCHAR(100) DEFAULT '',
    TRANGTHAI ENUM('Chưa xử lý', 'Đang xử lý', 'Đang vận chuyển', 'Giao hàng thành công', 'Đã hủy'),
    NGAYDATHANG DATE,
    TONGTIEN INT CHECK(TONGTIEN >= 0),
    PHUONGTHUCTHANHTOAN VARCHAR(100),
    IS_ACTIVE BIT DEFAULT 1,
    CONSTRAINT fk_donhang_accounts FOREIGN KEY (USERID) REFERENCES accounts(USERID)
);

CREATE TABLE chitietdonhang (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MADONHANG INT NOT NULL,
    MASANPHAM INT NOT NULL,
    SOLUONG INT NOT NULL,
    GIABAN INT NOT NULL CHECK(GIABAN >= 0),
    TONGTIEN INT NOT NULL CHECK(TONGTIEN >= 0),
    CONSTRAINT fk_donhang FOREIGN KEY (MADONHANG) REFERENCES donhang(MADONHANG),
    CONSTRAINT fk_sanpham FOREIGN KEY (MASANPHAM) REFERENCES sanpham(MASANPHAM)
);

CREATE TABLE feedback (
    FEEDBACKID INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT,
    NOIDUNG VARCHAR(255) NOT NULL,
    SOSAO INT NOT NULL,
    MASANPHAM INT,
    CONSTRAINT fk_spfb FOREIGN KEY (MASANPHAM) REFERENCES sanpham(MASANPHAM),
    CONSTRAINT fk_feedback_accounts FOREIGN KEY (USERID) REFERENCES accounts(USERID)
);

-- Example data

INSERT INTO loaisanpham (TENLOAISANPHAM) VALUES
('Điện thoại'),
('Máy tính xách tay'),
('Tai nghe'),
('Đồng hồ thông minh'),
('Phụ kiện'),
('Máy ảnh'),
('Loa Bluetooth');

INSERT INTO thuonghieu (TENTHUONGHIEU) VALUES
('Apple'),
('Samsung'),
('Xiaomi'),
('Sony'),
('Huawei'),
('Dell'),
('JBL');