CREATE DATABASE SHOPAPP;
USE SHOPAPP;

-- TẠO BẢNG
CREATE TABLE LOAISANPHAM 
(
    MALOAISANPHAM INT PRIMARY KEY AUTO_INCREMENT,
    TENLOAISANPHAM VARCHAR(255) NOT NULL
);

CREATE TABLE THUONGHIEU
(
	MATHUONGHIEU INT PRIMARY KEY AUTO_INCREMENT,
	TENTHUONGHIEU VARCHAR(40)
);

CREATE TABLE SANPHAM 
(
    MASANPHAM INT PRIMARY KEY AUTO_INCREMENT,
    TENSANPHAM VARCHAR(255) NOT NULL,
    GIA INT NOT NULL,
	MATHUONGHIEU INT NOT NULL,
    MOTA VARCHAR(500) DEFAULT '',
    SOLUONGTONKHO INT,
    NGAYTAO DATETIME,
    CHINHSUA DATETIME,
	MALOAISANPHAM INT,
    THUMBNAIL VARCHAR(300) DEFAULT '',
	CONSTRAINT FK_LOAISANPHAM FOREIGN KEY (MALOAISANPHAM) REFERENCES LOAISANPHAM(MALOAISANPHAM),
	CONSTRAINT FK_MATHUONGHIEU FOREIGN KEY (MATHUONGHIEU) REFERENCES THUONGHIEU(MATHUONGHIEU)
);

CREATE TABLE HINHANH
(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MASANPHAM INT,
    MALOAISANPHAM INT,
    TENHINHANH VARCHAR(300),
    CONSTRAINT FK_HINHANH_SANPHAM FOREIGN KEY(MASANPHAM) REFERENCES SANPHAM(MASANPHAM) ON DELETE CASCADE,
	CONSTRAINT FK_HINHANH_LOAISANPHAM FOREIGN KEY(MALOAISANPHAM) REFERENCES LOAISANPHAM(MALOAISANPHAM) ON DELETE CASCADE
);

CREATE TABLE ACCOUNTS
(
	USERID INT PRIMARY KEY AUTO_INCREMENT,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(100),
	FULLNAME VARCHAR(255) DEFAULT '',
	DIACHI VARCHAR(255) DEFAULT '',
	SODIENTHOAI VARCHAR(15) NOT NULL,
    NGAYTAO DATETIME,
    CHINHSUA DATETIME,
    NGAYSINH DATE,
    IS_ACTIVE BIT DEFAULT 1,
    FACEBOOK_ACCOUNT_ID INT DEFAULT 0,
    GOOGLE_ACCOUNT_ID INT DEFAULT 0,
	ROLENAME BIT
);

CREATE TABLE TOKENS
(
	TOKEN_ID INT PRIMARY KEY AUTO_INCREMENT,
    TOKEN VARCHAR(500) UNIQUE NOT NULL,
    TOKEN_TYPE VARCHAR(100) NOT NULL,
    EXPIRATION_DATE DATETIME,
    REVOKED BIT DEFAULT 1,
    EXPIRED BIT DEFAULT 1,
    USERID INT,
    CONSTRAINT FK_TOKENS_ACCOUNTS FOREIGN KEY (USERID) REFERENCES ACCOUNTS(USERID)
);

CREATE TABLE SOCIAL_ACCOUNTS
(
	SOCIAL_ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROVIDER VARCHAR(20) NOT NULL COMMENT 'TÊN NHÀ SOCIAL NETWORK',
    PROVIDER_ID VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL COMMENT 'EMAIL TÀI KHOẢN',
    NAME VARCHAR(100) NOT NULL COMMENT 'TÊN NGƯỜI DÙNG',
    USERID INT,
	CONSTRAINT FK_SOCIAL_ACCOUNTS_ACCOUNTS FOREIGN KEY (USERID) REFERENCES ACCOUNTS(USERID)
);

CREATE TABLE DONHANG (
    MADONHANG INT PRIMARY KEY AUTO_INCREMENT,
    USERID INT,
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) DEFAULT '',
    SODIENTHOAI VARCHAR(15) NOT NULL,
    DIACHI VARCHAR(200) NOT NULL,
    GHICHU VARCHAR(100) DEFAULT '',
    TRANGTHAI ENUM('Chua xu ly', 'Dang xu ly', 'Dang van chuyen', 'Giao hang thanh cong', 'Da huy'),
    NGAYDATHANG DATE,
    TONGTIEN INT,
    PHUONGTHUCTHANHTOAN VARCHAR(100),
    IS_ACTIVE BIT DEFAULT 1,
    CONSTRAINT FK_DONHANG_ACCOUNTS FOREIGN KEY (USERID) REFERENCES ACCOUNTS(USERID)
);

CREATE TABLE CHITIETDONHANG (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    MADONHANG INT NOT NULL,
    MASANPHAM INT NOT NULL,
    SOLUONG INT NOT NULL,
    GIABAN INT NOT NULL,
    TONGTIEN INT NOT NULL,
    CONSTRAINT FK_DONHANG FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG),
    CONSTRAINT FK_SANPHAM FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);

CREATE TABLE FEEDBACK (
    FEEDBACKID INT PRIMARY KEY AUTO_INCREMENT,
	USERID INT,
    NOIDUNG VARCHAR(255) NOT NULL,
    SOSAO INT NOT NULL,
    MASANPHAM INT,
    CONSTRAINT FK_SPFB FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM),
    CONSTRAINT FK_FEEDBACK_ACCOUNTS FOREIGN KEY (USERID) REFERENCES ACCOUNTS(USERID)
);

-- select các bảng
USE SHOPAPP;
SELECT * FROM ACCOUNTS;
SELECT * FROM CHITIETDONHANG;
SELECT * FROM DONHANG;
SELECT * FROM FEEDBACK;
SELECT * FROM HINHANH;
SELECT * FROM LOAISANPHAM;
SELECT * FROM SANPHAM;
SELECT * FROM SOCIAL_ACCOUNTS;
SELECT * FROM THUONGHIEU;
SELECT * FROM TOKENS;

drop database shopapp