CREATE TABLE IF NOT EXISTS coupons (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    active BIT NOT NULL DEFAULT true
);

ALTER TABLE donhang
ADD COLUMN coupon_id INT,
ADD CONSTRAINT FK_DONHANG_COUPON FOREIGN KEY (coupon_id) REFERENCES coupons(id);

ALTER TABLE chitietdonhang
ADD COLUMN coupon_id INT,
ADD CONSTRAINT FK_CHITIETDONHANG_COUPON FOREIGN KEY (coupon_id) REFERENCES coupons(id);

CREATE TABLE IF NOT EXISTS coupon_conditions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    coupon_id INT NOT NULL,
    attribute VARCHAR(255) NOT NULL,
    operator VARCHAR(10) NOT NULL,
    value VARCHAR(255) NOT NULL,
    discount_amount DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (coupon_id) REFERENCES coupons(id)
);